[package]
name = "serde_benches"
version = "0.1.0"
authors = ["Andrew J. Stone <andrew.j.stone.1@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
rmp = "0.8"
rmp-serde = "0.13"
bincode = "0.8"
serde_json = "1.0"
serde_cbor = "0.6"

